# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'component',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('nclicks', models.IntegerField(blank=True, null=True)),
                ('data', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'control',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CorsheadersCorsmodel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cors', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'corsheaders_corsmodel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzle.AuthUser')),
            ],
            options={
                'db_table': 'fan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fancomponent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nclicks', models.IntegerField(blank=True, null=True)),
                ('component', models.ForeignKey(blank=True, db_column='component', null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzle.Component')),
                ('fan', models.ForeignKey(blank=True, db_column='fan', null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzle.Fan')),
            ],
            options={
                'db_table': 'fancomponent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('place', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ip',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('src', models.CharField(blank=True, max_length=200)),
                ('rows', models.IntegerField(blank=True, null=True)),
                ('cols', models.IntegerField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('nclicks', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'puzzle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Puzzlefan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nclicks', models.IntegerField(blank=True, null=True)),
                ('fan', models.ForeignKey(blank=True, db_column='fan', null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzle.Fan')),
                ('puzzle', models.ForeignKey(blank=True, db_column='puzzle', null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzle.Puzzle')),
            ],
            options={
                'db_table': 'puzzlefan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reaction',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='puzzlefan',
            name='reaction',
            field=models.ForeignKey(blank=True, db_column='reaction', null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzle.Reaction'),
        ),
    ]
